name: Build Aspects Docker Images

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
env:
  TUTOR_ROOT: ./.ci/

jobs:
    build-aspects:
      runs-on: ubuntu-latest
      steps:
        - name: Log in to Docker Hub
          uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
          with:
            username: ${{ secrets.EDUNEXT_DOCKER_USERNAME }}
            password: ${{ secrets.EDUNEXT_DOCKER_PASSWORD }}
        - name: Checkout
          uses: actions/checkout@v3
        - name: setup python
          uses: actions/setup-python@v4
          with:
            python-version: 3.9
        - name: Install aspects
          run: pip install .
        - name: Save config
          run: tutor config save
        - name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Build Aspects Docker Images
          run: |
            tutor images build aspects --cache-to-registry
            tutor images push aspects
    build-superset:
      runs-on: ubuntu-latest
      steps:
        - name: Log in to Docker Hub
          uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
          with:
              username: ${{ secrets.EDUNEXT_DOCKER_USERNAME }}
              password: ${{ secrets.EDUNEXT_DOCKER_PASSWORD }}
        - name: Checkout
          uses: actions/checkout@v3
        - name: setup python
          uses: actions/setup-python@v4
          with:
            python-version: 3.9
        - name: Install aspects
          run: pip install .
        - name: Save config
          run: tutor config save
        - name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Build Superset Docker Image
          run: |
            tutor images build aspects-superset --cache-to-registry
            tutor images push aspects-superset
    build-openedx:
      runs-on: ubuntu-latest
      steps:
        - name: Log in to Docker Hub
          uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
          with:
              username: ${{ secrets.EDUNEXT_DOCKER_USERNAME }}
              password: ${{ secrets.EDUNEXT_DOCKER_PASSWORD }}
        - name: Checkout
          uses: actions/checkout@v3
        - name: setup python
          uses: actions/setup-python@v4
          with:
            python-version: 3.9
        - name: Install aspects
          run: pip install .
        - name: Save config
          run: tutor config save
        - name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Build Open edX Docker Images
          run: |
            tutor images build openedx --cache-to-registry
            tutor images push openedx
