name: Release
on:
  push:
    branches:
      - main

jobs:
  bumpversion:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag_version.outputs.new_version }}
      previous_tag: ${{ steps.tag_version.outputs.previous_tag }}
      bump_commit_sha: ${{ steps.bumpversion.outputs.commit_hash }}
    steps:
      - uses: actions/checkout@v3
      - name: Get next version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
          default_prerelease_bump: false
          dry_run: true
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Get current PR
        uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
      - name: Create bumpversion
        if: steps.tag_version.outputs.new_version
        run: |
          pip install bump2version
          bump2version --new-version ${{ steps.tag_version.outputs.new_version }} setup.cfg
      - name: Update Changelog
        if: steps.tag_version.outputs.new_version
        uses: stefanzweifel/changelog-updater-action@v1.6.2
        with:
          latest-version: ${{ steps.tag_version.outputs.new_tag }}
          release-notes: ${{ steps.tag_version.outputs.changelog }}
      - name: Commit bumpversion
        id: bumpversion
        if: steps.tag_version.outputs.new_version
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          branch: bot/${{steps.tag_version.outputs.new_version}}
          create_branch: true
          commit_message: "chore: preparing release ${{ steps.tag_version.outputs.new_version }}"
          file_pattern: CHANGELOG.md setup.cfg tutoraspects/*
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
            title: "chore: preparing release ${{ steps.tag_version.outputs.new_version }}"
            body: |
              Automated version bump for release ${{ steps.tag_version.outputs.new_version }}.

              This pull request was automatically generated. It includes the following changes:

              - Next version: ${{ steps.tag_version.outputs.new_version }}
              - Original pull request: ${{ steps.PR.outputs.number }}
              - Changelog: ${{ steps.tag_version.outputs.changelog }}

              No code changes are included in this pull request. The purpose of this PR is to trigger a version bump for the project.

              Once the pull request is merged, a new GitHub release will be created with the updated version.
            base: main
            labels: automated-pr
            branch: bot/${{steps.tag_version.outputs.new_version}}
            delete-branch: true
  release:
    needs: bumpversion
    if: needs.bumpversion.outputs.version
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag_version.outputs.new_tag }}
      changelog: ${{ steps.tag_version.outputs.changelog }}
    steps:
      - uses: actions/checkout@v3
      - name: Create tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_sha: ${{ needs.bumpversion.outputs.bump_commit_sha }}
          default_bump: false
          default_prerelease_bump: false
      - name: Create a GitHub release
        if: steps.tag_version.outputs.new_tag
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
