name: Test Tutor OARS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TUTOR_ROOT: ./.ci/

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install python reqs
        run: pip install -r requirements/dev.txt
      - name: Install oars
        run: pip install -e .
      - name: Tutor config save
        run: tutor config save
      - name: Populate Docker cache
        run: tutor images pull openedx
      - name: Tutor build openedx
        run: tutor images build openedx
      - name: Tutor init
        run: tutor local do init
      - name: Tutor start
        run: tutor local start -d
